version: '3'
services:
  zookeeper:
    container_name: zookeeper-container
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    hostname: zookeeper
    networks:
      - kafka-network

  kafka:
    container_name: kafka-container
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: messageTopic:3:1,logTopic:2:1 #topic:partition:replicas
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network
    depends_on:
      - zookeeper

networks:
  kafka-network:
    driver: "bridge"